#!/bin/sh

red='\033[0;31m'
green='\033[0;32m'
noColor='\033[0m'

# 工具区根目录
projectDir=$(git rev-parse --show-toplevel)
lintProjects=("HookGitCommitWithLintDemo")

for project in ${lintProjects[@]}
do
    # Android lint check
    echo "-------------- Starting run android lint for ${project} ---------------"
    lintReportPath="${project}/build/reports/lint-results.html"
    # 执行 lint，获取 lint error 数
    for issueCount in $(./gradlew ${project}:lint 2>/dev/null | grep "Ran lint on variant" | egrep -o '[0-9]+')
    do
        if [ $issueCount -ne 0 ]
        then
            echo "${red}Failed, ${project} project has ${issueCount} lint issues!${noColor}"
            echo "Please refer file://${projectDir}/${lintReportPath}"
            exit 1
        fi
    done
    echo "${green}Successed, no android lint issues found for ${project}${noColor}\n"
done